run_name: 'ts_extended_data'
outdir: null
resume: null

ema: True
wandb_params:
  mode: 'online'  # disabled, offline, online
  group: 'transition_states'
  project: 'chembl3d_megalodon_diffusion'

data:
  dataset_root: "/home/fnikitin/ts_dataset_batch_2"
  processed_folder: "processed"
  batch_size: &batch_size 150
  inference_batch_size: 150
  data_loader_type: "midi"
  aug_rotations: False
  scale_coords: &scale_coords 1.0

loss:
  variables:
    - variable_name: 'ts_coord'
      loss_scale: 3.0
      aggregate: 'mean'
      continuous: True
      use_distance: null
      distance_scale: null

interpolant:
  timesteps: &timesteps 100
  time_type: &time_type "discrete" #["discrete, "continuous]
  scheduler_type: &scheduler_type "cosine_adaptive" #["cosine_adaptive, "linear"]
  sample_time_method: "uniform" # ["symmetric", "uniform", "stab_mode", "logit_normal", "beta"]
  sample_time_mean: 0 # Used in stab_mode and logit_normal
  sample_time_scale: 0.81 # Used in stab_mode and logit_normal
  global_variable_name: 'ts_coord' # variable that is specficed below to be used for sampling time and loss sampling
  min_t: &min_t 0
  variables:
    - variable_name: 'ts_coord'
      interpolant_type: 'continuous_diffusion' #["continuous_diffusion", "continuous_flow_matching"]
      diffusion_type: 'vdm'
      prior_type: 'gaussian'
      timesteps: *timesteps
      num_classes: 3
      scheduler_type: *scheduler_type
      scheduler_cut: False
      time_type: *time_type
      nu: 2.5
      com_free: True
      min_t: *min_t
    - variable_name: 'numbers'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      num_classes: &num_atoms 54
      prior_type: null
    - variable_name: 'bmat_r'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      num_classes: 9
      prior_type: null
    - variable_name: 'bmat_p'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      num_classes: 9
      prior_type: null

    - variable_name: 'charges'
      interpolant_type: "discrete_null" #["discrete_diffusion", "discrete_flow_matching"]
      concat: 'numbers'
      num_classes: 7
      offset: 4
      prior_type: null



dynamics:
  model_name: "megav3ts"
  model_args:
    atom_classes: 61
    edge_classes: 9
    invariant_edge_feat_dim: 64
    invariant_node_feat_dim: 256
    n_vector_features: 64
    equivariant_node_feature_dim: 3
    num_layers: 10
    num_heads: 4
    dist_size: 16
    prune_edges: False
  wrapper_args:
    timesteps: *timesteps
    time_type: *time_type

self_conditioning:
  name: "base"
  variables:
    - variable_name: ts_coord
      hidden_dims: 32
      fuse_softmax: False
      vector: True
      clamp_min: -100
      clamp_max: 100

sample:
  node_distribution: null

train:
  seed: 48
  gpus: 1
  n_epochs: 800
  enable_progress_bar: True
  gradient_clip_value: 1.0
  log_freq: 50
  val_freq: 50
  checkpoint_monitor: "val/loss"
  checkpoint_monitor_mode: min
  checkpoint_every_n_train_steps: 500

evaluation:
  type: transition_states
  max_molecules: 200
  timesteps: *timesteps
  scale_coords: *scale_coords
  save_dir: 'ts_data'


optimizer:
  type: adamw
  lr: 1.e-4
  weight_decay: 1.e-12
  amsgrad: True

lr_scheduler:
  type: linear_warmup
  initial_lr: 1.e-5
  final_lr: 1.e-4
  num_warmup_steps: 1000
  interval: step
  frequency: 1 #not in config but this is the default

