run_name: 'ts_flow_extended_data'
outdir: null
resume: null

ema: True
wandb_params:
  mode: 'online'  # disabled, offline, online
  group: 'transition_states'
  project: 'chembl3d_megalodon_diffusion'

data:
  dataset_root: "/home/fnikitin/ts_dataset_batch_2"
  processed_folder: "processed"
  batch_size: &batch_size 150
  inference_batch_size: 150
  data_loader_type: "midi"
  aug_rotations: False
  scale_coords: &scale_coords 1.0

loss:
  use_loss_clamps: True
  loss_clamp_epoch_threshold: 10
  loss_clamps:
    ts_coord: 1.0
  variables:
    - variable_name: 'ts_coord'
      loss_scale: 1.0
      aggregate: 'mean'
      continuous: True
      loss_type: 'mse'
      use_distance: null
      distance_scale: null

interpolant:
  timesteps: &timesteps 25
  time_type: &time_type "continuous"
  sample_time_method: "uniform"
  sample_time_mean: 0
  sample_time_scale: 1.0
  global_variable_name: 'ts_coord'
  min_t: &min_t 0.0
  variables:
    - variable_name: 'ts_coord'
      interpolant_type: 'continuous_flow_matching' #["continuous_diffusion", "continuous_flow_matching"]
      prediction_type: 'velocity'
      optimal_transport: 'rigid' #'scale_ot'
      prior_type: 'gaussian'
      timesteps: *timesteps
      num_classes: 3
      scheduler_type: "linear"
      scheduler_cut: False
      time_type: *time_type
      min_t: *min_t
      com_free: True
      noise_sigma: 0.0
      inference_noise_sigma: 0.
    - variable_name: 'numbers'
      interpolant_type: "discrete_null"
      num_classes: &num_atoms 54
      prior_type: null
    - variable_name: 'bmat_r'
      interpolant_type: "discrete_null"
      num_classes: 9
      prior_type: null
    - variable_name: 'bmat_p'
      interpolant_type: "discrete_null"
      num_classes: 9
      prior_type: null
    - variable_name: 'charges'
      interpolant_type: "discrete_null"
      concat: 'numbers'
      num_classes: 7
      offset: 4
      prior_type: null

dynamics:
  model_name: "megav3ts"
  model_args:
    atom_classes: 61
    edge_classes: 9
    invariant_edge_feat_dim: 64
    invariant_node_feat_dim: 256
    n_vector_features: 64
    equivariant_node_feature_dim: 3
    num_layers: 10
    num_heads: 4
    dist_size: 16
    prune_edges: False
  wrapper_args:
    timesteps: *timesteps
    time_type: *time_type

sample:
  node_distribution: null
  return_step_output: true  # For GoFlow: return integrated position, not velocity

train:
  seed: 48
  gpus: 1
  n_epochs: 1000
  enable_progress_bar: True
  gradient_clip_value: 1.0
  log_freq: 50
  val_freq: 50
  checkpoint_monitor: "val/loss"
  checkpoint_monitor_mode: min
  checkpoint_every_n_train_steps: 500

evaluation:
  type: transition_states
  max_molecules: 200
  timesteps: *timesteps
  scale_coords: *scale_coords
  save_dir: "/home/fnikitin/TSMegaGen/data/${run_name}"

optimizer:
  type: adamw
  lr: 1.e-4
  weight_decay: 1.e-12
  amsgrad: True

lr_scheduler:
  type: linear_warmup
  initial_lr: 1.e-5
  final_lr: 1.e-4
  num_warmup_steps: 1000
  interval: step
  frequency: 1 #not in config but this is the default

